### ISSUE TITLE
Unexpected Identifier

### ISSUE THREAD

**Issue by appsparkler** [xpepermint/vue-cli-template#9]
@xpepermint I was trying to work with your template; however, after `npm run start` i got this error in *cmd*

```
 async listen () {
        ^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\projects\testProjects\sandboxes\vuess\src\index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by xpepermint** [comment]
I would say that you don't have `Node.js v7+`. Am I right?

**Comment by appsparkler** [comment]
yup.  I was about to _close_ this issue after i checked the `version`.  Thanks.  Will update and try it out.

**Comment by xpepermint** [comment]
Cool!
